### ISSUE TITLE
타입 이슈

### ISSUE THREAD

**Issue by pyj-pd** [chkim116/kadvice#6]
- TypeScript 버전: 4.9.3
- 패키지 버전: 2.0.1
- 설치 시 사용한 명령어: ```pnpm add kadvice```

안녕하세요. `kadvice` 모듈 임포트 시 타입스크립트가 해당 모듈을 인식하지 못하는 문제가 나타나고 있습니다.

![모듈 임포트 오류](https://github.com/chkim116/kadvice/assets/123401626/a1dc04ce-83dd-4ea9-aec0-951363e780ef)
![index.d.ts 파일에서 발생하는 오류](https://github.com/chkim116/kadvice/assets/123401626/91dc4920-9f57-4d0a-88c7-6d924574dbad)
![node_modules 폴더 구조](https://github.com/chkim116/kadvice/assets/123401626/9fdd990f-9731-4b9c-88a0-a4f717c43dc0)

**Comment by chkim116** [comment]
`package.json`에 있는 경로가 잘못되어 나타난 이슈입니다 #7 에서 수정하였으므로 클로징하겠습니다. 제보 감사합니다 🙇‍♂️
